basic:
  checkpoint: null # set to -1 to load last saved model
  headless: false
  max_iterations: 10000 # set the maximum number of learning iterations to train for
  sim_device: "cuda:2" # device for physics simulation
  rl_device: "cuda:2" # device for the RL algorithm
  seed: 42 # seed - set to -1 to choose random seed
  description: ""

env:
  num_envs: 4096
  num_observations: 47
  # - 重力方向 (3)
  # - 指令速度 (3)
  # - 基座状态（位置、速度、角速度）
  # - 关节位置 (12)
  # - 关节速度 (12)
  # - 上一次动作 (12)
  num_privileged_obs: 14
  num_actions: 12
  # 左腿：Hip_Roll, Hip_Yaw, Hip_Pitch, Knee_Pitch, Ankle_Pitch, Ankle_Roll
  # 右腿：同样6个
  env_spacing: 1.  # not used with plane terrain

runner:
  horizon_length: 24
  mini_epochs: 20
  save_interval: 500
  use_wandb: false

viewer:
  pos: [3., -3., 2.]  # [m]
  lookat: [0., 0., 0.]  # [m]
  record_video: true  # only in play
  record_interval: 5.  # [s]
  record_env_idx: 0

algorithm:
  learning_rate: 1.e-5
  gamma: 0.995
  lam: 0.95
  bound_coef: 1.0
  entropy_coef: -0.01
  symmetric_coef: 10.
  desired_kl: 0.01

sim:
  dt: 0.002
  substeps: 1
  up_axis: "z"
  gravity: [0.0, 0.0, -9.81]
  physics_engine: "physx" # "physx" or "flex"
  physx:
    num_threads: 4 # Number of worker threads per scene used by PhysX - for CPU PhysX only.
    solver_type: 1 # 0: pgs, 1: tgs
    num_position_iterations: 4
    num_velocity_iterations: 1
    contact_offset: 0.02
    rest_offset: 0.0
    bounce_threshold_velocity: 0.2
    max_depenetration_velocity: 100.0
    default_buffer_size_multiplier: 5.0
    max_gpu_contact_pairs: 8388608 # 8*1024*1024
    num_subscenes: 4 # Splits the simulation into N physics scenes and runs each one in a separate thread
    contact_collection: 1 # 0: CC_NEVER (don't collect contact info), 1: CC_LAST_SUBSTEP (collect only contacts on last substep), 2: CC_ALL_SUBSTEPS (broken - do not use!)

asset:
  file: "resources/T1/T1_locomotion.urdf"
  mujoco_file: "resources/T1/T1_locomotion.xml"
  name: "T1"
  base_name: "Trunk"
  foot_names: ["left_foot_link", "right_foot_link"]
  disable_gravity: false
  default_dof_drive_mode: 3 # see GymDofDriveModeFlags (0 is none, 1 is pos tgt, 2 is vel tgt, 3 effort)
  collapse_fixed_joints: true # bug: if collapse_fixed_joints = false, foot doesn't collide with ground
  fix_base_link: false # fix the base of the robot
  self_collisions: 0 # 1 to disable, 0 to enable...bitwise filter
  replace_cylinder_with_capsule: false # replace collision cylinders with capsules, leads to faster/more stable simulation
  flip_visual_attachments: false # Some .obj meshes must be flipped from y-up to z-up
  density: 0.001
  angular_damping: 0.
  linear_damping: 0.
  max_angular_velocity: 1000.
  max_linear_velocity: 1000.
  armature: 0.
  thickness: 0.01
  feet_edge_pos: [[ 0.1215,  0.05, -0.03],
                  [ 0.1215, -0.05, -0.03],
                  [-0.1015,  0.05, -0.03],
                  [-0.1015, -0.05, -0.03]] # x,y,z [m]

init_state:
  pos: [0.0, 0.0, 0.72] # x,y,z [m]
  rot: [0.0, 0.0, 0.0, 1.0] # x,y,z,w [quat]
  lin_vel: [0.0, 0.0, 0.0]  # x,y,z [m/s]
  ang_vel: [0.0, 0.0, 0.0]  # x,y,z [rad/s]
  default_joint_angles: {"Hip_Pitch": -0.2, "Knee_Pitch": 0.4, "Ankle_Pitch": -0.25, "default": 0.} # target angles when action = 0.0

control:
  stiffness: {"Hip": 160., "Knee": 120., "Ankle": 50.} # [N*m/rad]
  damping: {"Hip": 5., "Knee": 5., "Ankle": 1.} # [N*m*s/rad]
  action_scale: 1.
  decimation: 10

terrain:
  type: "trimesh" # "plane" or "trimesh"
  static_friction: 1.0  # [-]
  dynamic_friction: 1.0  # [-]
  restitution: 0.        # [-]
  # trimesh only:
  terrain_length: 10.
  terrain_width: 10.
  border_size: 5.
  num_terrains: 8
  terrain_proportions: [0.0, 0.0, 0.5, 0.5] # terrain types: [plane, slope, random, discrete]
  slope: 0.1
  random_height: 0.1
  discrete_height: 0.02
  horizontal_scale: 0.1
  vertical_scale: 0.005
  slope_threshold: 2.0

commands:
  num_commands: 3 # default: lin_vel_x, lin_vel_y, ang_vel_yaw
  still_proportion: 0.1
  lin_vel_x: [-1.0, 1.0] # min max [m/s]
  lin_vel_y: [-1.0, 1.0] # min max [m/s]
  ang_vel_yaw: [-1, 1]   # min max [rad/s]
  resampling_time_s: [8., 12.]
  gait_frequency: [1.0, 2.0] # min max [Hz]
  # curriculum only:
  curriculum: false
  update_rate: 0.1
  lin_vel_levels: 10
  ang_vel_levels: 10
  lin_vel_x_resolution: 0.2 # [m/s]
  lin_vel_y_resolution: 0.1 # [m/s]
  ang_vel_resolution: 0.2 # [rad/s]
  episode_length_toler: 0.1
  lin_vel_x_toler: 0.4 # [m/s]
  lin_vel_y_toler: 0.2 # [m/s]
  ang_vel_yaw_toler: 0.2 # [rad/s]

normalization:
  gravity: 1.0
  lin_vel: 1.0
  ang_vel: 1.0
  dof_pos: 1.0
  dof_vel: 0.1
  filter_weight: 0.1
  push_force: 0.1
  push_torque: 0.5
  clip_actions: 1.

noise:
  gravity:
    range: [0., 0.01]
    operation: "additive"
    distribution: "gaussian"
  lin_vel:
    range: [0., 0.05]
    operation: "additive"
    distribution: "gaussian"
  ang_vel:
    range: [0., 0.1]
    operation: "additive"
    distribution: "gaussian"
  dof_pos:
    range: [0., 0.01]
    operation: "additive"
    distribution: "gaussian"
  dof_vel:
    range: [0., 0.1]
    operation: "additive"
    distribution: "gaussian"
  height:
    range: [0., 0.02]
    operation: "additive"
    distribution: "gaussian"

randomization:
  init_dof_pos:
    range: [0., 0.05]
    operation: "additive"
    distribution: "gaussian"
  init_base_pos_xy:
    range: [-1., 1.]
    operation: "additive"
    distribution: "uniform"
  init_base_lin_vel_xy:
    range: [0., 0.1]
    operation: "additive"
    distribution: "gaussian"

  kick_interval_s: 2.
  kick_lin_vel:
    range: [0., 0.1]
    operation: "additive"
    distribution: "gaussian"
  kick_ang_vel:
    range: [0., 0.02]
    operation: "additive"
    distribution: "gaussian"

  push_interval_s: 5.
  push_duration_s: 1.
  push_force:
    range: [0., 10.]
    operation: "additive"
    distribution: "gaussian"
  push_torque:
    range: [0., 2.]
    operation: "additive"
    distribution: "gaussian"

  dof_stiffness:
    range: [0.95, 1.05]
    operation: "scaling"
    distribution: "uniform"
  dof_damping:
    range: [0.95, 1.05]
    operation: "scaling"
    distribution: "uniform"
  dof_friction:
    range: [0.0, 2.0]
    operation: "additive"
    distribution: "uniform"

  friction:
    range: [0.1, 2.0]
    operation: "additive"
    distribution: "uniform"
  compliance:
    range: [0.5, 1.5]
    operation: "additive"
    distribution: "uniform"
  restitution:
    range: [0.1, 0.9]
    operation: "additive"
    distribution: "uniform"

  base_com:
    range: [-0.1, 0.1]
    operation: "additive"
    distribution: "uniform"
  base_mass:
    range: [0.8, 1.2]
    operation: "scaling"
    distribution: "uniform"
  other_com:
    range: [-0.005, 0.005]
    operation: "additive"
    distribution: "uniform"
  other_mass:
    range: [0.98, 1.02]
    operation: "scaling"
    distribution: "uniform"

rewards:
  scales:
    survival: 0.25
    tracking_lin_vel_x: 1.5
    tracking_lin_vel_y: 1.5
    tracking_ang_vel: 4.0
    # tracking_ang_vel: 0.5
    base_height: -13.
    orientation: -3.
    torques: -3.e-4
    torque_tiredness: -1.e-2
    power: -2.e-3
    # torques: -2.e-4
    # torque_tiredness: -1.e-2
    # power: -2.e-3
    lin_vel_z: -2.
    ang_vel_xy: -0.7
    # ang_vel_xy: -0.2
    dof_vel: -1.e-4
    dof_acc: -1.e-7
    root_acc: -3.e-4
    action_rate: -1.5
    # action_rate: -1.
    dof_pos_limits: -1.
    dof_vel_limits: -0.
    torque_limits: -0.
    collision: -1.
    feet_slip: -0.1
    feet_vel_z: -0.
    feet_yaw_diff: -1.
    feet_yaw_mean: -1.
    feet_roll: -0.2
    feet_distance: -2.
    feet_swing: 5.   
    # feet_distance: -1.
    # feet_swing: 3.
  episode_length_s: 30.
  terminate_height: 0.45
  terminate_vel: 50.
  terminate_contacts_on: []
  penalize_contacts_on: ["Trunk", "H1", "H2", "AL", "AR", "Waist", "Hip", "Shank", "Ankle"]
  only_positive_rewards: true # if true negative total rewards are clipped at zero (avoids early termination problems)
  tracking_sigma: 0.25 # tracking reward = exp(-error^2/sigma)
  base_height_target: 0.75
  soft_dof_pos_limit: 1. # percentage of urdf limits, values above this limit are penalized
  soft_dof_vel_limit: 1.
  soft_torque_limit: 1.
  swing_period: 0.2
  feet_distance_ref: 0.2
